# https://github.com/zeke/semantic-pull-requests

# By default types specified in commitizen/conventional-commit-types is used.
# See: https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json
# 默认情况下，无需配置

# Always validate the PR title, and ignore the commits
titleOnly: true

# You can override the valid types
types:
  - feat
  - fix
  - docs
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - chore
  - revert
